// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportTrack.AccessDatos;

#nullable disable

namespace SportTrack_v1.AccesoDatos.Migrations
{
    [DbContext(typeof(SportTrackDbContext))]
    [Migration("20260412215802_AddBoteIdentificadorToInscripcion")]
    partial class AddBoteIdentificadorToInscripcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Bote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique()
                        .HasDatabaseName("IX_Botes_Tipo");

                    b.ToTable("Botes", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Kayak Individual"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Kayak Doble"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Kayak Cuadruple"
                        },
                        new
                        {
                            Id = 4,
                            Tipo = "Canoa Individual"
                        },
                        new
                        {
                            Id = 5,
                            Tipo = "Canoa Doble"
                        },
                        new
                        {
                            Id = 6,
                            Tipo = "Canoa Cuadruple"
                        });
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EdadMax")
                        .HasColumnType("integer");

                    b.Property<int?>("EdadMin")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Nombre");

                    b.ToTable("Categorias", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdadMax = 10,
                            EdadMin = 9,
                            Nombre = "Pre-Infantil"
                        },
                        new
                        {
                            Id = 2,
                            EdadMax = 11,
                            EdadMin = 10,
                            Nombre = "Infantil"
                        },
                        new
                        {
                            Id = 3,
                            EdadMax = 13,
                            EdadMin = 12,
                            Nombre = "Menor"
                        },
                        new
                        {
                            Id = 4,
                            EdadMax = 15,
                            EdadMin = 14,
                            Nombre = "Cadete"
                        },
                        new
                        {
                            Id = 5,
                            EdadMax = 17,
                            EdadMin = 16,
                            Nombre = "Junior"
                        },
                        new
                        {
                            Id = 6,
                            EdadMax = 22,
                            EdadMin = 18,
                            Nombre = "Sub-23"
                        },
                        new
                        {
                            Id = 7,
                            EdadMax = 35,
                            EdadMin = 18,
                            Nombre = "Senior"
                        },
                        new
                        {
                            Id = 8,
                            EdadMax = 49,
                            EdadMin = 40,
                            Nombre = "Master A"
                        },
                        new
                        {
                            Id = 9,
                            EdadMax = 59,
                            EdadMin = 50,
                            Nombre = "Master B"
                        },
                        new
                        {
                            Id = 10,
                            EdadMax = 80,
                            EdadMin = 60,
                            Nombre = "Master C"
                        });
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Clubes_Nombre");

                    b.ToTable("Clubes", "catalogos");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Distancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanciaRegata")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistanciaRegata")
                        .IsUnique()
                        .HasDatabaseName("IX_Distancias_DistanciaRegata");

                    b.ToTable("Distancias", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanciaRegata = 1
                        },
                        new
                        {
                            Id = 2,
                            DistanciaRegata = 2
                        },
                        new
                        {
                            Id = 3,
                            DistanciaRegata = 3
                        },
                        new
                        {
                            Id = 4,
                            DistanciaRegata = 4
                        },
                        new
                        {
                            Id = 5,
                            DistanciaRegata = 5
                        },
                        new
                        {
                            Id = 6,
                            DistanciaRegata = 6
                        },
                        new
                        {
                            Id = 7,
                            DistanciaRegata = 7
                        },
                        new
                        {
                            Id = 8,
                            DistanciaRegata = 8
                        },
                        new
                        {
                            Id = 9,
                            DistanciaRegata = 9
                        },
                        new
                        {
                            Id = 10,
                            DistanciaRegata = 10
                        },
                        new
                        {
                            Id = 11,
                            DistanciaRegata = 11
                        },
                        new
                        {
                            Id = 12,
                            DistanciaRegata = 12
                        },
                        new
                        {
                            Id = 13,
                            DistanciaRegata = 13
                        },
                        new
                        {
                            Id = 14,
                            DistanciaRegata = 14
                        },
                        new
                        {
                            Id = 15,
                            DistanciaRegata = 15
                        },
                        new
                        {
                            Id = 16,
                            DistanciaRegata = 16
                        });
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Programada");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaFinInscripciones")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Eventos_Estado");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Eventos_Fecha");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Eventos_Nombre");

                    b.ToTable("Eventos", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Programada");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxParticipantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Pista")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PruebaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_EventoPruebas_Estado");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_EventoPruebas_FechaHora");

                    b.HasIndex("PruebaId");

                    b.HasIndex("EventoId", "PruebaId", "FechaHora")
                        .IsUnique()
                        .HasDatabaseName("IX_EventoPruebas_EventoPrueba_Fecha");

                    b.ToTable("EventoPruebas", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoteIdentificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Carril")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCabezaDeSerie")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Inscrito");

                    b.Property<int>("EventoPruebaId")
                        .HasColumnType("integer");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NumeroCompetidor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NumeroManga")
                        .HasColumnType("integer");

                    b.Property<int?>("ParticipanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Carril")
                        .HasDatabaseName("IX_Inscripciones_Carril");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Inscripciones_Estado");

                    b.HasIndex("FechaInscripcion")
                        .HasDatabaseName("IX_Inscripciones_FechaInscripcion");

                    b.HasIndex("NumeroCompetidor")
                        .HasDatabaseName("IX_Inscripciones_NumeroCompetidor");

                    b.HasIndex("ParticipanteId")
                        .HasDatabaseName("IX_Inscripciones_ParticipanteId");

                    b.HasIndex("EventoPruebaId", "ParticipanteId", "Fase")
                        .IsUnique()
                        .HasDatabaseName("IX_Inscripciones_Unica_Fase")
                        .HasFilter("\"ParticipanteId\" IS NOT NULL");

                    b.ToTable("Inscripciones", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.InscripcionTripulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PosicionEnBote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("InscripcionId", "ParticipanteId")
                        .IsUnique()
                        .HasDatabaseName("IX_InscripcionTripulantes_Unica");

                    b.ToTable("InscripcionTripulantes", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SexoId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClubId")
                        .HasDatabaseName("IX_Participantes_ClubId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Participantes_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Pais")
                        .HasDatabaseName("IX_Participantes_Pais");

                    b.HasIndex("SexoId")
                        .HasDatabaseName("IX_Participantes_SexoId");

                    b.HasIndex("Nombre", "Apellido")
                        .HasDatabaseName("IX_Participantes_NombreApellido");

                    b.ToTable("Participantes", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Penalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("JuezAsignado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResultadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan?>("TiempoPenalizacion")
                        .HasColumnType("interval");

                    b.Property<string>("TipoPenalizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("JuezAsignado")
                        .HasDatabaseName("IX_Penalizaciones_JuezAsignado");

                    b.HasIndex("ResultadoId")
                        .HasDatabaseName("IX_Penalizaciones_ResultadoId");

                    b.HasIndex("Severidad")
                        .HasDatabaseName("IX_Penalizaciones_Severidad");

                    b.HasIndex("TipoPenalizacion")
                        .HasDatabaseName("IX_Penalizaciones_TipoPenalizacion");

                    b.HasIndex("ResultadoId", "TipoPenalizacion")
                        .HasDatabaseName("IX_Penalizaciones_ResultadoTipo");

                    b.ToTable("Penalizaciones", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Prueba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoteId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DistanciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SexoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DistanciaId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Pruebas_Nombre");

                    b.HasIndex("SexoId");

                    b.HasIndex("BoteId", "CategoriaId", "DistanciaId", "SexoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Pruebas_Unica");

                    b.ToTable("Pruebas", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<TimeSpan?>("TiempoOficial")
                        .HasColumnType("interval");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("VelocidadMedia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Resultados_Estado");

                    b.HasIndex("InscripcionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Resultados_InscripcionId");

                    b.HasIndex("Posicion")
                        .HasDatabaseName("IX_Resultados_Posicion");

                    b.HasIndex("Puntos")
                        .HasDatabaseName("IX_Resultados_Puntos");

                    b.HasIndex("InscripcionId", "Posicion")
                        .HasDatabaseName("IX_Resultados_InscripcionPosicion");

                    b.ToTable("Resultados", "regatas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Sexos_Nombre");

                    b.ToTable("Sexos", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Femenino"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mixto"
                        });
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", "seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@sporttrack.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$12$R9h/lSAbvI125hcnyqvQDu9fAKDLn6Y8yK/.Vz0uI3492M0h0mY3.",
                            Rol = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Evento", "Evento")
                        .WithMany("EventoPruebas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventoPruebas_Eventos");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Prueba", "Prueba")
                        .WithMany("EventoPruebas")
                        .HasForeignKey("PruebaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventoPruebas_Pruebas");

                    b.Navigation("Evento");

                    b.Navigation("Prueba");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Inscripcion", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.EventoPrueba", "EventoPrueba")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoPruebaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Inscripciones_EventoPruebas");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Participante", "Participante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Inscripciones_Participantes");

                    b.Navigation("EventoPrueba");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.InscripcionTripulante", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Inscripcion", "Inscripcion")
                        .WithMany("Tripulantes")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InscripcionTripulantes_Inscripciones");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InscripcionTripulantes_Participantes");

                    b.Navigation("Inscripcion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Participante", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Categoria", "Categoria")
                        .WithMany("Participantes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Participantes_Categorias");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Club", "Club")
                        .WithMany("Participantes")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Participantes_Clubes");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Sexo", "Sexo")
                        .WithMany("Participantes")
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Participantes_Sexos");

                    b.Navigation("Categoria");

                    b.Navigation("Club");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Penalizacion", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Resultado", "Resultado")
                        .WithMany("Penalizaciones")
                        .HasForeignKey("ResultadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Penalizaciones_Resultados");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Prueba", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Bote", "Bote")
                        .WithMany("Pruebas")
                        .HasForeignKey("BoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Botes");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Categoria", "Categoria")
                        .WithMany("Pruebas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Categorias");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Distancia", "Distancia")
                        .WithMany("Pruebas")
                        .HasForeignKey("DistanciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Distancias");

                    b.HasOne("SportTrack_v1.Entidades.Entidades.Sexo", "Sexo")
                        .WithMany("Pruebas")
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Sexos");

                    b.Navigation("Bote");

                    b.Navigation("Categoria");

                    b.Navigation("Distancia");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Resultado", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Inscripcion", "Inscripcion")
                        .WithOne("Resultado")
                        .HasForeignKey("SportTrack_v1.Entidades.Entidades.Resultado", "InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Resultados_Inscripciones");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Usuario", b =>
                {
                    b.HasOne("SportTrack_v1.Entidades.Entidades.Club", "Club")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Bote", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Categoria", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Club", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Distancia", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Evento", b =>
                {
                    b.Navigation("EventoPruebas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Inscripcion", b =>
                {
                    b.Navigation("Resultado");

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Participante", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Prueba", b =>
                {
                    b.Navigation("EventoPruebas");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Resultado", b =>
                {
                    b.Navigation("Penalizaciones");
                });

            modelBuilder.Entity("SportTrack_v1.Entidades.Entidades.Sexo", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Pruebas");
                });
#pragma warning restore 612, 618
        }
    }
}
