using System;
using Npgsql;

class Program
{
    static void Main()
    {
        string connString = "Host=dpg-d7ih1pd7vvec73abm5sg-a.virginia-postgres.render.com;Port=5432;Database=db_sporttrack;Username=db_sporttrack_user;Password=WGOFP4V6h11iv2GXhWZ4SLViVfyr8Ljf;SSL Mode=Require;Trust Server Certificate=true";
        try
        {
            using var conn = new NpgsqlConnection(connString);
            conn.Open();
            Console.WriteLine("Conexión exitosa.");

            Console.WriteLine("Agregando columna PlanSaaSId...");
            using (var cmd = new NpgsqlCommand("ALTER TABLE catalogos.\"Clubes\" ADD COLUMN IF NOT EXISTS \"PlanSaaSId\" integer;", conn))
            {
                cmd.ExecuteNonQuery();
            }
            
            Console.WriteLine("Creando tabla PlanesSaaS...");
            string createTable = @"
                CREATE TABLE IF NOT EXISTS catalogos.""PlanesSaaS"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Nombre"" character varying(50) NOT NULL,
                    ""Precio"" numeric(18,2) NOT NULL,
                    ""MaxAtletas"" integer NOT NULL,
                    ""MaxTorneosActivos"" integer NOT NULL,
                    ""ResultadosTiempoReal"" boolean NOT NULL,
                    ""ExportacionExcel"" boolean NOT NULL,
                    ""SoportePrioritario"" boolean NOT NULL,
                    CONSTRAINT ""PK_PlanesSaaS"" PRIMARY KEY (""Id"")
                );";
            using (var cmd = new NpgsqlCommand(createTable, conn))
            {
                cmd.ExecuteNonQuery();
            }

            Console.WriteLine("Insertando planes semilla...");
            string insertData = @"
                INSERT INTO catalogos.""PlanesSaaS"" (""Id"", ""ExportacionExcel"", ""MaxAtletas"", ""MaxTorneosActivos"", ""Nombre"", ""Precio"", ""ResultadosTiempoReal"", ""SoportePrioritario"")
                VALUES (1, FALSE, 500, 1, 'Básico', 0.0, FALSE, FALSE),
                       (2, TRUE, 2000, 5, 'Estándar', 50.0, TRUE, FALSE),
                       (3, TRUE, -1, -1, 'Premium', 120.0, TRUE, TRUE)
                ON CONFLICT (""Id"") DO NOTHING;";
            using (var cmd = new NpgsqlCommand(insertData, conn))
            {
                cmd.ExecuteNonQuery();
            }

            Console.WriteLine("Columnas actuales en catalogos.Clubes:");
            using (var cmd = new NpgsqlCommand("SELECT column_name FROM information_schema.columns WHERE table_schema = 'catalogos' AND table_name = 'Clubes';", conn))
            using (var reader = cmd.ExecuteReader())
            {
                while (reader.Read()) Console.WriteLine("- " + reader.GetString(0));
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}
